#!/usr/bin/env python3
"""Compare the v2 predictor with v1 on every split both studies have run.

Writes into ``--results-dir/report/``:

``comparison.csv``          one row per (experiment, split): v1 and v2 metrics side by side
``table_comparison.tex``    booktabs table (MAE, R^2, device accuracy, regret + baselines)
``fig_regret_lofo.pdf/png`` per-family regret of v1, v2 and the two baselines
``comparison_summary.json`` averages over the leave-one-family-out folds

Safe on a partial study: splits missing on either side are listed with ``--``.
"""

from __future__ import annotations

import argparse
import logging
import statistics
import sys
from pathlib import Path
from typing import Any

import _bootstrap  # noqa: F401

from gsv2 import paths

paths.ensure_v1_imports()

from genstudy import paths as v1_paths  # noqa: E402
from genstudy import report  # noqa: E402
from genstudy.io import save_csv, save_json, save_text, setup_logging  # noqa: E402

logger = logging.getLogger("make_report_v2")

EXPERIMENTS = (
    ("random_control", "Random split (control)"),
    ("leave_one_family_out", "Leave-one-family-out"),
    ("size_extrapolation", "Size extrapolation"),
)
METRICS = ("mae", "r2", "device_choice_accuracy", "fidelity_regret_mean")


def _by_split(results_dir: Path, experiment: str, gt_path: Path) -> dict[str, dict[str, Any]]:
    exp_dir = results_dir / experiment
    results = report.collect_split_metrics(exp_dir)
    report.add_baseline_regrets(results, exp_dir, gt_path)
    return {r["split"]: r["test"] for r in results}


def _fmt(value: Any, digits: int) -> str:
    return f"{value:.{digits}f}" if isinstance(value, (int, float)) else "--"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--results-dir", type=Path, default=paths.RESULTS_DIR)
    parser.add_argument("--v1-results-dir", type=Path, default=paths.V1_RESULTS_DIR)
    parser.add_argument("--gt-path", type=Path,
                        default=v1_paths.MODEL_DIR / "expected_fidelity_results_benchmark.json")
    parser.add_argument("--label", default="tab:ml4qc:generalization-v2")
    args = parser.parse_args()

    report_dir = args.results_dir / "report"
    setup_logging(report_dir / "make_report.log")
    logger.info("Command line: %s", " ".join(sys.argv))

    rows: list[dict[str, Any]] = []
    for experiment, _ in EXPERIMENTS:
        v1 = _by_split(args.v1_results_dir, experiment, args.gt_path)
        v2 = _by_split(args.results_dir, experiment, args.gt_path)
        for split in sorted(set(v1) | set(v2), key=lambda s: -(v2.get(s) or v1[s])["n_circuits"]):
            ref = v2.get(split) or v1[split]
            row: dict[str, Any] = {"experiment": experiment, "split": split,
                                   "n_test": ref["n_circuits"]}
            for tag, side in (("v1", v1.get(split)), ("v2", v2.get(split))):
                for m in METRICS:
                    row[f"{tag}_{m}"] = side[m] if side else ""
            row["regret_best_fixed_device"] = ref.get("regret_best_fixed_device", "")
            row["regret_random_device"] = ref.get("regret_random_device", "")
            rows.append(row)
    save_csv(rows, report_dir / "comparison.csv")

    # --- LaTeX ---------------------------------------------------------------
    header = ["Split", r"$n$",
              r"MAE v1", r"MAE v2", r"$R^2$ v1", r"$R^2$ v2",
              r"Acc.\ v1", r"Acc.\ v2", r"Regret v1", r"Regret v2",
              r"Regret$_\text{fixed}$", r"Regret$_\text{rand}$"]
    lines = [r"% Generated by evaluations/generalization_v2/scripts/make_report.py",
             r"\begin{table*}[t]", r"\centering",
             r"\caption{Fidelity predictor v1 (three fixed outputs, linear fidelity, uniform "
             r"sampling, random validation) versus v2 (device-graph encoder, log-fidelity "
             r"target, family-balanced sampling, out-of-distribution validation) on the same "
             r"splits. Regret$_\text{fixed}$: always the single best device of the test set; "
             r"Regret$_\text{rand}$: uniformly random device.}",
             r"\label{" + args.label + "}",
             r"\begin{tabular}{l" + "r" * (len(header) - 1) + "}", r"\toprule",
             " & ".join(header) + r" \\"]
    for experiment, title in EXPERIMENTS:
        block = [r for r in rows if r["experiment"] == experiment]
        if not block:
            continue
        lines += [r"\midrule", r"\multicolumn{%d}{l}{\textit{%s}} \\" % (len(header), title)]
        for r in block:
            cells = [r["split"].replace("_", r"\_"), str(r["n_test"])]
            for m, digits in (("mae", 4), ("r2", 3), ("device_choice_accuracy", 3),
                              ("fidelity_regret_mean", 4)):
                cells += [_fmt(r[f"v1_{m}"], digits), _fmt(r[f"v2_{m}"], digits)]
            cells += [_fmt(r["regret_best_fixed_device"], 4), _fmt(r["regret_random_device"], 4)]
            lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    save_text("\n".join(lines) + "\n", report_dir / "table_comparison.tex")

    # --- Summary and figure over the LOFO folds -----------------------------
    lofo = [r for r in rows if r["experiment"] == "leave_one_family_out"
            and r["v1_mae"] != "" and r["v2_mae"] != ""]
    summary: dict[str, Any] = {"n_folds_both": len(lofo)}
    if lofo:
        for tag in ("v1", "v2"):
            summary[tag] = {m: statistics.fmean(r[f"{tag}_{m}"] for r in lofo) for m in METRICS}
            summary[tag]["folds_beating_fixed_device"] = sum(
                r[f"{tag}_fidelity_regret_mean"] < r["regret_best_fixed_device"] for r in lofo)
        summary["regret_best_fixed_device_mean"] = statistics.fmean(
            r["regret_best_fixed_device"] for r in lofo)
        summary["regret_random_device_mean"] = statistics.fmean(
            r["regret_random_device"] for r in lofo)
        _plot_regret(lofo, report_dir)
    save_json(summary, report_dir / "comparison_summary.json")
    logger.info("Report written to %s", report_dir)
    return 0


def _plot_regret(rows: list[dict[str, Any]], out_dir: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    names = [r["split"] for r in rows]
    series = [("v1", "v1_fidelity_regret_mean", "#8C8C8C"),
              ("v2", "v2_fidelity_regret_mean", "#4C72B0"),
              ("best fixed device", "regret_best_fixed_device", "#DD8452"),
              ("random device", "regret_random_device", "#C44E52")]
    x = np.arange(len(names))
    width = 0.2
    fig, ax = plt.subplots(figsize=(max(6, 0.9 * len(names) + 2), 3.6))
    for k, (label, key, color) in enumerate(series):
        ax.bar(x + (k - 1.5) * width, [r[key] for r in rows], width, label=label, color=color)
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha="right")
    ax.set_ylabel("Mean fidelity regret")
    ax.set_title("Leave-one-family-out: device-choice regret")
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(out_dir / f"fig_regret_lofo.{ext}", dpi=200)
    plt.close(fig)


if __name__ == "__main__":
    raise SystemExit(main())
